{
  imports = [
    ./blink-cmp
    ./bufferline.nix
    ./colorizer.nix
    ./comment.nix
    ./precognition.nix
    ./friendly-snippets.nix
    ./gitsigns-nvim.nix
    ./lsp.nix
    ./lsp-lines.nix
    ./lualine.nix
    ./modicator.nix
    ./nvim-autopairs.nix
    ./render-markdown.nix
    ./snacks
    ./statuscol.nix
    ./telescope.nix
    ./treesitter.nix
    ./web-devicons.nix
    ./which-key.nix
    ./whitespace.nix
  ];
}
