{
  imports = [
    #./aider.nix
    ./blink-cmp
    ./bufferline.nix
    ./colorizer.nix
    ./comment.nix
    #./codecompanion.nix
    ./friendly-snippets.nix
    ./fugitive.nix
    ./gitsigns-nvim.nix
    ./grug-far.nix
    ./lsp
    ./lsp-lines.nix
    ./lualine.nix
    ./modicator.nix
    ./neo-tree.nix
    ./nvim-autopairs.nix
    ./nvim-dap
    #./opencode.nix
    ./precognition.nix
    ./render-markdown.nix
    ./snacks
    ./statuscol.nix
    ./telescope.nix
    ./treesitter.nix
    ./web-devicons.nix
    ./which-key.nix
    ./whitespace.nix
  ];
}
